### ISSUE TITLE
Bug in StateSimilarityMap

### ISSUE THREAD

**Issue by arr28** [SteveDraper/ggp-base#188]
Steve,

Eclipse has spotted a problem in `StateSimilarityMap.getTopMoves`.  The outermost for loop can only ever run one time.  (Identified as `nearbyHashIndex++` being dead code.)  Although `SSHG.hashSize` is 16 and therefore the apparent intention that we go through this loop 17 times, we actually only go through it once because there's a return statement (`return (int)(totalWeight);`) as the last statement in the loop body (and no `continue` statements).

I don't suppose this is what you intended, but am reluctant to touch it because I don't understand it at all.

Would you like to take look?

Andrew

**Comment by arr28** [comment]
Steve - I think you've dealt with this.  Good to close?

**Comment by SteveDraper** [comment]
Yup!
